### ISSUE TITLE
About the groundtruth of KITTI

### ISSUE THREAD

**Issue by ghoshaw** [utiasSTARS/sun-bcnn-vo#1]
What is the coordinate of the groundtruth of the KITTI ?

**Comment by leeclemnet** [comment]
The raw KITTI ground truth poses are given in an [earth-centred, earth-fixed (ECEF) coordinate system](https://en.wikipedia.org/wiki/ECEF). For convenience, we subtract off the initial position of each sequence so that the initial position is always (0,0,0), but we keep the East-North-Up (ENU) coordinate frame for expressing the vehicle orientation and sun vectors.

**Comment by ghoshaw** [comment]
Thanks,  the file you given is the raw KITTI groundtruth (ECEF) or your version(ENU)? 
 If it is your version, does that mean "2011_10_03/2011_10_03_drive_0027_sync/image_02/data/0000000000.png,0.23639,-0.57199,-0.78546" , E = 0.23, N = -0.57, U = -0.78? 
And the ENU is like this one?
![default](https://user-images.githubusercontent.com/23494873/35377061-bb854dfc-01e8-11e8-8e30-70379ea423e9.PNG)
https://en.wikipedia.org/wiki/North_east_down,  (the image in right hand)

**Comment by leeclemnet** [comment]
Ah, sorry, I misunderstood your question. I thought you were asking about the KITTI ground truth poses in general, not the sun vectors provided by Sun-BCNN.

The sun vectors in `kitti_sun_test_00.csv`, for example, are given in the camera-centric coordinate system where +x points to the right of the image, +y points downwards, and +z points outward from the camera into the world, like this:

![](https://www.mathworks.com/help/vision/gs/depthtopointcloud_coordinate.png)

So in your example,
`2011_10_03/2011_10_03_drive_0027_sync/image_02/data/0000000000.png,0.23639,-0.57199,-0.78546` means x=0.236, y=-0.572, z=0.785, which means that the sun is to the right of the camera (+x), above the camera (-y) and in front of the camera (+z).

**Comment by ghoshaw** [comment]
Thank you very much!
